import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Helmet } from 'react-helmet-async';
import { BookOpen, Calendar, Clock, ArrowRight, Sparkles, User, ArrowLeft, Share2, Bookmark } from 'lucide-react';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  author: string;
  readTime: string;
  category: string;
  role: string;
}

const MOCK_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Optimizing Industrial IoT with Edge Computing',
    excerpt: 'Discover how edge computing reduces latency and bandwidth usage in large-scale manufacturing environments.',
    content: `
      <h2>The Shift to the Edge</h2>
      <p>As industrial automation scales, the sheer volume of data generated by thousands of sensors exceeds the capacity of traditional cloud-only architectures. Edge computing brings processing power closer to the data source, transforming raw sensor pulses into actionable intelligence in milliseconds.</p>
      
      <h3>Why Latency Matters</h3>
      <p>In a smart factory, a delay of even 100ms in detecting an overheating bearing can mean the difference between a routine maintenance stop and a catastrophic system failure. By processing "Hot Paths" at the edge, Nexus Protocol ensures safety-critical decisions are made locally.</p>
      
      <p>Edge nodes act as the first line of defense, filtering out noise and only forwarding high-value analytical data to the Nexus Core for long-term storage and model training.</p>
    `,
    date: 'May 12, 2026',
    author: 'Dr. Sarah Chen',
    role: 'Chief Architect',
    readTime: '6 min',
    category: 'Architecture'
  },
  {
    id: '2',
    title: 'The Future of Predictive Maintenance',
    excerpt: 'How AI-driven telemetry analysis is preventing costly downtime before it even happens.',
    content: `
      <h2>Beyond Maintenance Schedules</h2>
      <p>Traditional maintenance is reactive or based on static timelines. Both are inefficient. Predictive maintenance uses machine learning to identify the discrete signatures of wear before they manifest as failures.</p>
      
      <h3>The AI Signature</h3>
      <p>Our latest models can detect micro-vibrations and thermal fluctuations that are invisible to traditional monitoring systems. By cross-referencing these with historical failure data, Nexus can predict hardware end-of-life with 94% accuracy.</p>
    `,
    date: 'May 08, 2026',
    author: 'Marco Rossi',
    role: 'ML Engineer',
    readTime: '4 min',
    category: 'Intelligence'
  },
  {
    id: '3',
    title: 'Securing the Smart Grid: Nexus Protocol v2',
    excerpt: 'An in-depth look at our new quantum-resistant encryption layer for critical infrastructure.',
    content: `
      <h2>A New Era of Threats</h2>
      <p>The digitalization of utility grids has opened new attack vectors. Nexus Protocol v2 introduces post-quantum cryptography (PQC) to ensure that the secrets of today remain safe from the computers of tomorrow.</p>
      
      <h3>Layered Defense</h3>
      <p>Security isn't a single wall; it's an ecosystem. Our new protocol implements hardware-root-of-trust verification for every device node before it can join the logical mesh.</p>
    `,
    date: 'May 01, 2026',
    author: 'Elena Vance',
    role: 'Security lead',
    readTime: '8 min',
    category: 'Security'
  }
];

export function BlogView() {
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);

  if (selectedPost) {
    return (
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="p-10 max-w-4xl mx-auto space-y-12"
      >
        <button 
          onClick={() => setSelectedPost(null)}
          className="flex items-center gap-3 text-slate-400 hover:text-white p-2 transition-all font-mono text-[10px] uppercase tracking-[0.2em] group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Archive_Index
        </button>

        <header className="space-y-10">
          <div className="space-y-6">
            <div className="flex items-center gap-4">
              <span className="px-5 py-1.5 bg-brand-accent/10 text-brand-accent border border-brand-accent/20 rounded-full font-mono text-[10px] uppercase tracking-[0.2em] font-bold transition-all">
                {selectedPost.category}
              </span>
              <span className="text-slate-500 font-mono text-[10px] uppercase font-bold tracking-[0.2em]">{selectedPost.readTime} Analysis</span>
            </div>
            <h2 className="text-7xl font-bold text-white light:text-slate-900 tracking-tight leading-[0.9] uppercase transition-colors font-display">
              {selectedPost.title}
            </h2>
          </div>

          <div className="flex items-center justify-between py-10 border-y border-white/5 light:border-slate-900/5 transition-all">
            <div className="flex items-center gap-6">
              <div className="w-14 h-14 bg-white/[0.03] light:bg-brand-panel/30 border border-white/10 light:border-slate-200 rounded-2xl flex items-center justify-center text-white light:text-slate-900 transition-all">
                <User className="w-8 h-8" />
              </div>
              <div>
                <div className="text-2xl font-bold text-white light:text-slate-900 uppercase tracking-tight transition-colors font-display">{selectedPost.author}</div>
                <div className="text-[11px] font-mono text-slate-500 light:text-slate-600 uppercase font-bold tracking-[0.2em] mt-1.5">{selectedPost.role} // {selectedPost.date}</div>
              </div>
            </div>
            <div className="flex gap-4">
              <button className="p-4 border border-white/5 rounded-2xl text-slate-400 hover:bg-white/5 hover:text-white transition-all">
                <Share2 className="w-6 h-6" />
              </button>
              <button className="p-4 border border-white/5 rounded-2xl text-slate-400 hover:bg-white/5 hover:text-white transition-all">
                <Bookmark className="w-6 h-6" />
              </button>
            </div>
          </div>
        </header>

        <div className="relative">
          <article 
            className="prose prose-invert light:prose-neutral max-w-none transition-colors duration-500
              prose-headings:text-white light:prose-headings:text-slate-900 prose-headings:uppercase prose-headings:tracking-tight prose-headings:font-bold
              prose-p:text-slate-300 light:prose-p:text-slate-600 prose-p:leading-relaxed prose-p:text-lg
              prose-strong:text-white light:prose-strong:text-slate-900 prose-strong:font-bold"
            dangerouslySetInnerHTML={{ __html: selectedPost.content }}
          />
        </div>

        <footer className="pt-24 border-t border-white/5 light:border-slate-900/5 transition-all">
          <div className="panel-bg p-12 flex flex-col md:flex-row items-center justify-between gap-10 border-white/10 light:border-slate-300 bg-white/[0.02] light:bg-brand-panel">
            <div className="flex items-center gap-8">
              <div className="w-20 h-20 bg-brand-accent/10 border border-brand-accent/20 rounded-3xl flex items-center justify-center text-brand-accent shadow-glow transition-all hover:scale-110">
                <Sparkles className="w-10 h-10" />
              </div>
              <div>
                <div className="text-3xl font-bold text-white light:text-slate-900 uppercase tracking-tight transition-colors font-display">Transmission_Sync</div>
                <div className="text-lg text-slate-500 font-medium max-w-md mt-2">Subscribe to the Nexus Transmission for deep-tech industrial intelligence and firmware updates.</div>
              </div>
            </div>
            <button className="px-10 py-6 bg-brand-accent text-brand-bg rounded-[2rem] font-bold uppercase tracking-[0.2em] text-sm shadow-glow hover:brightness-110 transition-all active:scale-95">
              Initialize Sync
            </button>
          </div>
        </footer>
      </motion.div>
    );
  }

  return (
    <div className="p-10 max-w-7xl mx-auto space-y-20 bg-transparent h-full">
      <Helmet>
        <title>Nexus Archives | Industrial IoT Blog</title>
        <meta name="description" content="Deep dives into IoT infrastructure, edge-security protocols, and high-latency industrial intelligence nodes." />
      </Helmet>
      <header className="space-y-6">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-brand-accent/10 border border-brand-accent/20 text-brand-accent rounded-xl shadow-glow transition-all">
            <BookOpen className="w-6 h-6" />
          </div>
          <h2 className="text-6xl font-bold tracking-tight text-white light:text-slate-900 uppercase leading-none transition-colors font-display">Archives</h2>
        </div>
          <p className="font-mono text-[11px] uppercase tracking-[0.4em] text-slate-500 light:text-slate-600 font-bold leading-relaxed">
          Deep dives into IoT infrastructure, edge-security protocols, and high-latency industrial intelligence nodes.
        </p>
      </header>

      {/* Featured Post */}
      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        onClick={() => setSelectedPost(MOCK_POSTS[0])}
        className="panel-bg p-12 flex flex-col lg:flex-row gap-12 group cursor-pointer border-white/5 light:border-slate-300 bg-white/[0.02] light:bg-brand-panel hover:border-brand-accent/30 overflow-hidden relative transition-all"
      >
        <div className="lg:w-1/2 aspect-square bg-white/[0.03] light:bg-slate-900/[0.03] rounded-[2rem] border border-white/5 light:border-slate-900/5 relative overflow-hidden transition-all">
          <div className="absolute inset-0 bg-brand-accent/5 mix-blend-overlay" />
          <div className="absolute inset-0 flex items-center justify-center">
            <Sparkles className="w-48 h-48 text-brand-accent opacity-5" />
          </div>
          <div className="absolute top-0 left-0 px-6 py-3 bg-brand-accent text-brand-bg font-mono text-[10px] uppercase font-bold tracking-[0.3em] rounded-br-[2rem] shadow-glow z-10 transition-all">
            PRIORITY_NODE
          </div>
        </div>
        <div className="lg:w-1/2 flex flex-col justify-center space-y-8">
          <div className="flex items-center gap-4 font-mono text-[10px] text-brand-accent uppercase tracking-widest font-bold">
            <span>{MOCK_POSTS[0].category}</span>
            <div className="w-1.5 h-1.5 bg-brand-accent/30 rounded-full" />
            <span className="text-slate-600 light:text-slate-500 font-medium transition-colors">{MOCK_POSTS[0].readTime} read</span>
          </div>
          <h3 className="text-6xl font-bold text-white light:text-slate-900 tracking-tight leading-[0.95] group-hover:text-brand-accent transition-colors uppercase transition-colors font-display">
            {MOCK_POSTS[0].title}
          </h3>
            <p className="text-slate-500 light:text-slate-600 text-xl leading-relaxed font-medium">
            {MOCK_POSTS[0].excerpt}
          </p>
          <div className="flex items-center justify-between pt-10 border-t border-white/5 light:border-slate-900/5 group-hover:border-brand-accent/20 transition-all">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-white/[0.05] light:bg-slate-900/[0.05] border border-white/10 light:border-slate-900/10 rounded-2xl flex items-center justify-center text-white light:text-slate-900 transition-all">
                <User className="w-6 h-6" />
              </div>
              <div>
                <div className="text-lg font-bold text-white light:text-slate-900 uppercase tracking-tight transition-colors">{MOCK_POSTS[0].author}</div>
                <div className="text-[10px] font-mono text-slate-500 uppercase font-bold tracking-widest mt-1">{MOCK_POSTS[0].date}</div>
              </div>
            </div>
            <div className="p-4 border border-white/5 light:border-slate-900/5 rounded-2xl text-white light:text-slate-900 group-hover:bg-brand-accent group-hover:text-brand-bg group-hover:border-brand-accent transition-all shadow-glow">
              <ArrowRight className="w-6 h-6" />
            </div>
          </div>
        </div>
      </motion.div>

      {/* Post Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        {MOCK_POSTS.slice(1).map((post, i) => (
          <motion.div
            key={post.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 * (i + 1) }}
            onClick={() => setSelectedPost(post)}
            className="panel-bg p-10 group cursor-pointer transition-all border-white/5 light:border-slate-300 bg-white/[0.02] light:bg-brand-panel hover:border-brand-accent/30 flex flex-col relative overflow-hidden"
          >
            <div className="flex items-center gap-4 mb-8">
              <span className="font-mono text-[10px] uppercase px-4 py-1 border border-white/10 light:border-slate-900/10 rounded-full text-slate-400 font-bold tracking-widest group-hover:border-brand-accent/30 group-hover:text-brand-accent transition-all">
                {post.category}
              </span>
              <div className="flex items-center gap-2 text-[10px] font-mono text-slate-600 light:text-slate-500 uppercase font-bold tracking-widest transition-colors">
                <Clock className="w-4 h-4" />
                {post.readTime}
              </div>
            </div>
            <h4 className="text-4xl font-bold text-white light:text-slate-900 mb-6 group-hover:text-brand-accent transition-colors uppercase tracking-tight leading-none transition-colors font-display">
              {post.title}
            </h4>
            <p className="text-slate-500 light:text-slate-600 text-base leading-relaxed mb-12 line-clamp-2 font-medium transition-colors">
              {post.excerpt}
            </p>
            <div className="mt-auto flex items-center justify-between pt-8 border-t border-white/5 light:border-slate-900/5 group-hover:border-brand-accent/20 transition-all">
              <div className="text-[10px] font-mono text-slate-600 light:text-slate-500 uppercase flex items-center gap-3 font-bold tracking-widest transition-colors">
                <Calendar className="w-4 h-4" />
                {post.date}
              </div>
              <ArrowRight className="w-5 h-5 text-white light:text-slate-900 group-hover:translate-x-1 group-hover:text-brand-accent transition-all" />
            </div>
            {/* Background glow */}
            <div className="absolute -bottom-4 -right-4 w-24 h-24 bg-brand-accent/5 blur-3xl rounded-full pointer-events-none transition-all" />
          </motion.div>
        ))}
      </div>
    </div>
  );
}

